import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const root = fileURLToPath(new URL('../', import.meta.url));
const hash = text => createHash('sha256').update(text).digest('hex');
const knownTypes = new Set(['selector', 'relation', 'string', 'color', 'icon-path', 'enum', 'enum-list', 'number', 'boolean', 'block']);

export function generate(manifestText, schemaText) {
  const manifest = JSON.parse(manifestText), schema = JSON.parse(schemaText);
  if (manifest.language !== 'spytial-layout-spec' || !Array.isArray(manifest.items) || !Array.isArray(manifest.blocks)) throw Error('Unrecognized core manifest format.');
  if (!/^\d+\.\d+\.\d+(?:-[\w.-]+)?$/.test(manifest.spytialCoreVersion)) throw Error('Core manifest must contain an exact version.');
  if (schema['x-spytial-core-version'] !== manifest.spytialCoreVersion || schema['x-spytial-language-version'] !== manifest.languageVersion) throw Error('Core manifest and schema versions do not match.');
  const names = new Set(), blockNames = new Set(manifest.blocks.map(b => b.name));
  const checkField = f => {
    if (!knownTypes.has(f.type)) throw Error(`Unsupported manifest field type ${f.type}; update the generator before syncing.`);
    if (f.type === 'block' && !blockNames.has(f.block)) throw Error(`Unknown block ${f.block}.`);
    if (f.type.startsWith('enum') && !Array.isArray(f.values)) throw Error(`Missing enum values for ${f.name}.`);
  };
  for (const b of manifest.blocks) b.fields.forEach(checkField);
  for (const item of manifest.items) {
    if (!/^[a-z][a-zA-Z0-9]*$/.test(item.yamlKey) || names.has(item.yamlKey)) throw Error(`Invalid or duplicate helper name ${item.yamlKey}.`);
    names.add(item.yamlKey);
    if (!['mapping', 'scalar'].includes(item.valueShape) || item.sections.length !== 1 || !['constraints', 'directives'].includes(item.sections[0])) throw Error(`Unsupported shape/section for ${item.yamlKey}.`);
    if (item.valueShape === 'scalar' && item.fields.length !== 1) throw Error(`Unsupported scalar ${item.yamlKey}.`);
    item.fields.forEach(checkField);
  }
  const metadata = { coreVersion: manifest.spytialCoreVersion, languageVersion: manifest.languageVersion, hold: manifest.hold, source: manifest.source, blocks: manifest.blocks, items: manifest.items };
  const banner = '// Generated by scripts/generate.mjs. Do not edit; run npm run codegen.\n';
  const exports = manifest.items.map(i => `/** ${i.deprecated ? '@deprecated ' : ''}${i.description.replaceAll('*/', '* /')} */\nexport function ${i.yamlKey}(...args) { return makeRule(${JSON.stringify(i.yamlKey)}, args); }`).join('\n\n');
  const typeOf = f => ({ selector: 'string', relation: 'string', string: 'string', color: 'string', 'icon-path': 'string', number: 'number', boolean: 'boolean', block: `${f.block}Options`, enum: f.values?.map(JSON.stringify).join(' | '), 'enum-list': `readonly (${f.values?.map(JSON.stringify).join(' | ')})[]` })[f.type];
  const fieldsType = fields => fields.map(f => `  ${f.name}${f.required ? '' : '?'}: ${typeOf(f)};`).join('\n');
  const declarations = [
    '// Generated by scripts/generate.mjs. Do not edit.',
    'import type { Rule } from "../rules.js";',
    'export interface Source { text: string; location?: string; }',
    ...manifest.blocks.map(b => `export interface ${b.name}Options {\n${fieldsType(b.fields)}\n}`),
    ...manifest.items.flatMap(i => {
      if (i.valueShape === 'scalar') return [`export function ${i.yamlKey}(value: ${typeOf(i.fields[0])}): Rule;`];
      const params = i.fields.filter(f => f.required), extras = i.fields.filter(f => !f.required);
      const common = `${i.supportsHold ? '\n  hold?: "always" | "never";' : ''}${manifest.source.supportedBy.includes(i.id) ? '\n  source?: Source;' : ''}`;
      return [`export interface ${i.yamlKey}Options {\n${fieldsType(i.fields)}${common}\n}`, `export function ${i.yamlKey}(options: ${i.yamlKey}Options): Rule;`, ...(params.length ? [`export function ${i.yamlKey}(${params.map(f => `${f.name}: ${typeOf(f)}`).join(', ')}, options?: {\n${fieldsType(extras)}${common}\n}): Rule;`] : [])];
    }), '',
  ].join('\n');
  const reference = `# Generated rule helpers\n\nGenerated from spytial-core ${manifest.spytialCoreVersion}, language ${manifest.languageVersion}.\n\nEvery mapping helper accepts a core-shaped options object. Positional shortcuts follow\nthe manifest's required fields, with an optional final options object. Selectors are\npassed through unchanged. Deprecated forms remain available but are marked below.\n\n| Helper | Positional form | Section | Status |\n| --- | --- | --- | --- |\n${manifest.items.map(i => `| \`${i.yamlKey}\` | \`${i.yamlKey}(${i.valueShape === 'scalar' ? 'value' : i.fields.filter(f => f.required).map(f => f.name).concat('options').join(', ')})\` | ${i.sections[0]} | ${i.deprecated ? `Deprecated; use ${i.deprecated.replacedBy}` : 'Current'} |`).join('\n')}\n\nHelpers return immutable rule descriptors. Unknown fields, missing required fields,\ninvalid enum values, contradictory directions, and invalid numeric ranges throw early.\nCore remains responsible for selector evaluation and layout semantics. The object form\nis the stable escape hatch if upstream changes which fields are required.\n`;
  return new Map([
    ['src/generated/catalog.js', `${banner}export const catalog = ${JSON.stringify(metadata, null, 2)};\n`],
    ['src/generated/helpers.js', `${banner}import { makeRule } from '../rules.js';\n\n${exports}\n`],
    ['src/generated/helpers.d.ts', declarations],
    ['src/generated/core-version.js', `${banner}export const CORE_VERSION = ${JSON.stringify(manifest.spytialCoreVersion)};\nexport const LANGUAGE_VERSION = ${JSON.stringify(manifest.languageVersion)};\n`],
    ['vendor/core/lock.json', `${JSON.stringify({ coreVersion: manifest.spytialCoreVersion, languageVersion: manifest.languageVersion, manifestSha256: hash(manifestText), schemaSha256: hash(schemaText) }, null, 2)}\n`],
    ['docs/rule-helpers.md', reference],
  ]);
}

export async function writeOutputs(outputs, base = root) {
  for (const [file, content] of outputs) {
    await mkdir(path.dirname(path.join(base, file)), { recursive: true });
    await writeFile(path.join(base, file), content);
  }
}

async function main() {
  if (process.argv.slice(2).some(a => a !== '--check')) throw Error('Usage: node scripts/generate.mjs [--check]');
  const [manifest, schema] = await Promise.all(['spytial-language.json', 'spytial-spec.schema.json'].map(name => readFile(path.join(root, 'vendor/core', name), 'utf8')));
  const outputs = generate(manifest, schema);
  if (process.argv.includes('--check')) {
    const stale = [];
    for (const [file, content] of outputs) if (await readFile(path.join(root, file), 'utf8').catch(() => null) !== content) stale.push(file);
    if (stale.length) throw Error(`Generated files are stale: ${stale.join(', ')}. Run npm run codegen.`);
    console.log('Generated files match the pinned core manifest.');
  } else { await writeOutputs(outputs); console.log(`Generated ${outputs.size} files.`); }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch(e => { console.error(e.message); process.exitCode = 1; });
